# Generated by Django 4.2 on 2023-05-01 05:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tweetlike',
            unique_together={('user', 'tweet')},
        ),
    ]
